#!/usr/bin/env bash
set -euo pipefail
export COMET_API_KEY="wKvWIXBmWdm5O9w8buIWrqKEV"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

bash "$SCRIPT_DIR/muon_adam__trapezoid.sh"
bash "$SCRIPT_DIR/muon_adam__trapezoid_cosine.sh"
bash "$SCRIPT_DIR/muon_adam__trapezoid_cosine_min10.sh"
bash "$SCRIPT_DIR/muon_adam__cosine.sh"
bash "$SCRIPT_DIR/muon_adam__cosine_min10.sh"
bash "$SCRIPT_DIR/muon_adam__linear.sh"
bash "$SCRIPT_DIR/muon_adam__constant.sh"
bash "$SCRIPT_DIR/muon_adam__rsqrt.sh"
bash "$SCRIPT_DIR/muon_adamw__trapezoid.sh"
bash "$SCRIPT_DIR/muon_adamw__trapezoid_cosine.sh"
bash "$SCRIPT_DIR/muon_adamw__trapezoid_cosine_min10.sh"
bash "$SCRIPT_DIR/muon_adamw__cosine.sh"
bash "$SCRIPT_DIR/muon_adamw__cosine_min10.sh"
bash "$SCRIPT_DIR/muon_adamw__linear.sh"
bash "$SCRIPT_DIR/muon_adamw__constant.sh"
bash "$SCRIPT_DIR/muon_adamw__rsqrt.sh"
bash "$SCRIPT_DIR/muon_steps3__trapezoid.sh"
bash "$SCRIPT_DIR/muon_steps3__trapezoid_cosine.sh"
bash "$SCRIPT_DIR/muon_steps3__trapezoid_cosine_min10.sh"
bash "$SCRIPT_DIR/muon_steps3__cosine.sh"
bash "$SCRIPT_DIR/muon_steps3__cosine_min10.sh"
bash "$SCRIPT_DIR/muon_steps3__linear.sh"
bash "$SCRIPT_DIR/muon_steps3__constant.sh"
bash "$SCRIPT_DIR/muon_steps3__rsqrt.sh"
bash "$SCRIPT_DIR/muon_steps10__trapezoid.sh"
bash "$SCRIPT_DIR/muon_steps10__trapezoid_cosine.sh"
bash "$SCRIPT_DIR/muon_steps10__trapezoid_cosine_min10.sh"
bash "$SCRIPT_DIR/muon_steps10__cosine.sh"
bash "$SCRIPT_DIR/muon_steps10__cosine_min10.sh"
bash "$SCRIPT_DIR/muon_steps10__linear.sh"
bash "$SCRIPT_DIR/muon_steps10__constant.sh"